# Generated by Django 3.2.10 on 2021-12-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writeups', '0003_auto_20211210_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
